### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alphapapa** [ahungry/fast-scroll#2]
Hi,

Thanks for sharing this package.  Quick suggestion:

https://github.com/ahungry/fast-scroll/blob/1d4c9112b6ce62ef20897ebc40a97f09b97053c6/fast-scroll.el#L55

Working on `ts.el`, I found that `format-time-string` is surprisingly expensive.  It might be faster to use `current-time` in this package.

If you decide to keep `format-time-string`, I'm guessing `string-to-number` would be faster than `read`.

**Comment by ahungry** [comment]
Thanks, I'll consider that.

**Comment by ahungry** [comment]
Updated to use string-to-number over read.  If a bottleneck is on this polling function ever, I'll revisit the alternative current-time or encode-time builtins.

Thanks!
